name: Deploy OpenParser Server

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: [1, 2, 3]  # 3 instances for OpenParser server
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install httpx asyncio fastapi uvicorn aiofiles pyyaml xmltodict
    
    - name: Create .env file
      run: |
        echo "DNS_SERVER_URL=${{ secrets.DNS_SERVER_URL }}" >> .env
        echo "HOST=${{ secrets.HOST }}" >> .env
        echo "BASE_PORT=5007" >> .env
        echo "PORT=$(( 5007 + ${{ matrix.instance }} ))" >> .env
        echo "INSTANCE_ID=${{ matrix.instance }}" >> .env
        echo "ENV=production" >> .env
        echo "DEBUG=False" >> .env
        # OpenParser specific configurations
        echo "MAX_FILE_SIZE=10485760" >> .env  # 10MB
        echo "TEMP_DIR=/tmp/openparser" >> .env
        echo "SUPPORTED_FORMATS=json,xml,yaml,csv,markdown" >> .env
    
    - name: Start Server and Monitor
      run: |
        # Create temp directory
        mkdir -p /tmp/openparser
        
        # Start server with DNS integration
        python server.py &
        SERVER_PID=$!
        
        # Health check loop
        while true; do
          if ! kill -0 $SERVER_PID 2>/dev/null; then
            echo "Server crashed, exiting..."
            exit 1
          fi
          
          # Get current busy status and parser info
          HEALTH=$(curl -s "http://localhost:$(( 5007 + ${{ matrix.instance }} ))/health")
          BUSY=$(echo $HEALTH | jq -r .busy)
          PARSERS=$(curl -s "http://localhost:$(( 5007 + ${{ matrix.instance }} ))/parsers")
          
          # Log status
          echo "Instance ${{ matrix.instance }} status: $BUSY"
          echo "Available parsers: $(echo $PARSERS | jq -c .)"
          
          sleep 60
        done 