name: Deploy LLM Server

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: [1, 2, 3, 4, 5]  # 5 instances for LLM server
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install httpx asyncio fastapi uvicorn
    
    - name: Create .env file
      run: |
        echo "DNS_SERVER_URL=${{ secrets.DNS_SERVER_URL }}" >> .env
        echo "HOST=${{ secrets.HOST }}" >> .env
        echo "BASE_PORT=5000" >> .env
        echo "PORT=$(( 5000 + ${{ matrix.instance }} ))" >> .env
        echo "INSTANCE_ID=${{ matrix.instance }}" >> .env
        echo "ENV=production" >> .env
        echo "DEBUG=False" >> .env
        # LLM specific configurations
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
        echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> .env
        echo "COHERE_API_KEY=${{ secrets.COHERE_API_KEY }}" >> .env
        echo "DEFAULT_MODEL=${{ secrets.DEFAULT_MODEL }}" >> .env
    
    - name: Start Server and Monitor
      run: |
        # Start server with DNS integration
        python server.py &
        SERVER_PID=$!
        
        # Health check loop
        while true; do
          if ! kill -0 $SERVER_PID 2>/dev/null; then
            echo "Server crashed, exiting..."
            exit 1
          fi
          
          # Get current busy status
          BUSY=$(curl -s "http://localhost:$(( 5000 + ${{ matrix.instance }} ))/health" | jq -r .busy)
          
          # Log status
          echo "Instance ${{ matrix.instance }} status: $BUSY"
          
          sleep 60
        done 