name: Deploy Android Bridge Server

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: [1, 2, 3]  # 3 instances for Android Bridge server
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install httpx asyncio fastapi uvicorn websockets
    
    - name: Create .env file
      run: |
        echo "DNS_SERVER_URL=${{ secrets.DNS_SERVER_URL }}" >> .env
        echo "HOST=${{ secrets.HOST }}" >> .env
        echo "BASE_PORT=5005" >> .env
        echo "PORT=$(( 5005 + ${{ matrix.instance }} ))" >> .env
        echo "INSTANCE_ID=${{ matrix.instance }}" >> .env
        echo "ENV=production" >> .env
        echo "DEBUG=False" >> .env
        # Android Bridge specific configurations
        echo "WS_HEARTBEAT_INTERVAL=30" >> .env
        echo "MAX_CONNECTIONS=1000" >> .env
        echo "AUTH_KEY=${{ secrets.ANDROID_BRIDGE_AUTH_KEY }}" >> .env
    
    - name: Start Server and Monitor
      run: |
        # Start server with DNS integration
        python server.py &
        SERVER_PID=$!
        
        # Health check loop
        while true; do
          if ! kill -0 $SERVER_PID 2>/dev/null; then
            echo "Server crashed, exiting..."
            exit 1
          fi
          
          # Get current busy status and connection count
          HEALTH=$(curl -s "http://localhost:$(( 5005 + ${{ matrix.instance }} ))/health")
          BUSY=$(echo $HEALTH | jq -r .busy)
          DEVICES=$(curl -s "http://localhost:$(( 5005 + ${{ matrix.instance }} ))/devices" | jq -r .count)
          
          # Log status
          echo "Instance ${{ matrix.instance }} status: $BUSY (Connected devices: $DEVICES)"
          
          sleep 60
        done 