name: 24/7 Deployment

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install uvicorn
          
      - name: Start server
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          nohup uvicorn server:app --host 0.0.0.0 --port 8000 &
          echo $! > server.pid
          
      - name: Health check
        run: |
          sleep 10  # Wait for server to start
          curl -f http://localhost:8000/health || exit 1
          
      - name: Monitor and auto-restart
        run: |
          while true; do
            if ! curl -s http://localhost:8000/health > /dev/null; then
              echo "Server down, restarting..."
              kill $(cat server.pid)
              nohup uvicorn server:app --host 0.0.0.0 --port 8000 &
              echo $! > server.pid
              sleep 10
            fi
            sleep 60
          done
