name: Deploy Face Auth Server

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: [1, 2]  # 2 instances for face auth server
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install httpx asyncio fastapi uvicorn python-multipart
    
    - name: Create .env file
      run: |
        echo "DNS_SERVER_URL=${{ secrets.DNS_SERVER_URL }}" >> .env
        echo "HOST=${{ secrets.HOST }}" >> .env
        echo "BASE_PORT=5003" >> .env
        echo "PORT=$(( 5003 + ${{ matrix.instance }} ))" >> .env
        echo "INSTANCE_ID=${{ matrix.instance }}" >> .env
        echo "ENV=production" >> .env
        echo "DEBUG=False" >> .env
        # Face Auth specific configurations
        echo "FACE_RECOGNITION_MODEL=${{ secrets.FACE_RECOGNITION_MODEL }}" >> .env
        echo "MIN_CONFIDENCE=0.85" >> .env
        echo "FACE_DB_PATH=/data/faces" >> .env
    
    - name: Start Server and Monitor
      run: |
        # Create face database directory
        mkdir -p /data/faces
        
        # Start server with DNS integration
        python server.py &
        SERVER_PID=$!
        
        # Health check loop
        while true; do
          if ! kill -0 $SERVER_PID 2>/dev/null; then
            echo "Server crashed, exiting..."
            exit 1
          fi
          
          # Get current busy status
          BUSY=$(curl -s "http://localhost:$(( 5003 + ${{ matrix.instance }} ))/health" | jq -r .busy)
          
          # Log status
          echo "Instance ${{ matrix.instance }} status: $BUSY"
          
          sleep 60
        done

